version: "3.8"
services:
  mysql:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: test_pagination_db
    ports:
      - 5010:3306
    volumes:
      - ./test/seed/mysql.sql:/docker-entrypoint-initdb.d/seed.sql